stages:
  - build
  - deploy
  - test

variables:
  SERVER_REGISTRY_PATH: 0xhzx/cs590-final-server:latest
  UI_REGISTRY_PATH: 0xhzx/cs590-final-ui:latest

build-ui:
  stage: build
  before_script:
    - echo $UI_REGISTRY_PATH
    - echo $PWD
  script:
    - cd ui
    - echo "===================Building UI==================="
    - docker build -t $UI_REGISTRY_PATH .

build-server:
  stage: build
  before_script:
    - echo $SERVER_REGISTRY_PATH
    - echo $PWD
  script:
    - cd server
    - echo "===================Building Server==================="
    - docker build -t $SERVER_REGISTRY_PATH .


deploy:
  stage: deploy
  script:
    - kubectl delete -f k8s/
    - kubectl create -f k8s/

e2e-test: 
  stage: test
  script:
    - echo "===================Start running E2E tests==================="
    - npm --version
    - node --version
    - npm install @playwright/test
    - npx playwright install
    - npx playwright test --headed --project=webkit
    - echo "E2E tests complete."
  artifacts:
    when: always
    paths: 
      - playwright-report/index.html
