apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: server
  name: server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - image: 0xhzx/cs590-final-server:latest
        name: server
        # imagePullPolicy: Always
        imagePullPolicy: Never
        ports:
        - containerPort: 8191
          name: server
        env:
        - name: HOST
          value: localhost
        - name: EXTERNAL_PORT
          value: "80"
        - name: DISABLE_SECURITY
          value: "foo-bar-baz"
        # env:
        # - name: MONGO_URL
        #   value: mongodb://db
