apiVersion: v1
kind: Service
metadata:
  labels:
    app: ui
  name: ui
spec:
  type: LoadBalancer
  selector:
    app: ui
  ports:
  - name: "ui-service"
    port: 80
    targetPort: 80
    # nodePort: 31000
